import type { Metadata } from "next";
import AdminSidebar from "./components/AdminSidebar";
import AdminBody from "./components/AdminBody";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminPanelLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="AdminPanelContainer">
      <AdminSidebar />
      <AdminBody>{children}</AdminBody>
    </div>
  );
}
